### ISSUE TITLE
The application layout is not mobile friendly

### ISSUE THREAD

**Issue by pedrorubio** [epeicher/vote-me-up#2]
The layout on mobile devices with small screens could be improved as the current layout is difficult to use. See the screenshot below for an example of this.

![vote me up - current mobile layout](https://user-images.githubusercontent.com/15387155/41201363-ccc9729e-6cb6-11e8-8089-baf14d1ca69e.png)

**Comment by pedrorubio** [comment]
A [new pull request](https://github.com/epeicher/vote-me-up/pull/3) as has been created with a proposal for a new mobile layout based on cards (see screenshot below).

![vote me up - new mobile layout](https://user-images.githubusercontent.com/15387155/41201709-108ad6b6-6cbd-11e8-884a-20ad1a1abdcc.png)

**Comment by epeicher** [comment]
#3
